-- ============================================================
-- v21 — PENJAGAAN UJIAN IELTS
--
-- Untuk basis data yang SUDAH terlanjur dibuat dari 01-adzkia-postgres.sql
-- versi lama. Basis data baru tidak memerlukannya: berkas 01 sudah memuat
-- seluruh isi berkas ini.
--
-- Aman dijalankan berulang kali.
--
--     psql -d adzkia -f db/02-penjagaan-ielts.sql
--
-- Padanan `tambahKolom(...)` v21 pada versi SQLite (src/lib/db.ts).
-- ============================================================

BEGIN;

-- Kolom penjagaan, kembar dengan kolom senama di `attempts`.
ALTER TABLE ielts_pengerjaan ADD COLUMN IF NOT EXISTS subtes_aktif  text;
ALTER TABLE ielts_pengerjaan ADD COLUMN IF NOT EXISTS digugurkan_at timestamptz;
ALTER TABLE ielts_pengerjaan ADD COLUMN IF NOT EXISTS alasan_gugur  text;
ALTER TABLE ielts_pengerjaan ADD COLUMN IF NOT EXISTS denyut_at     timestamptz;
ALTER TABLE ielts_pengerjaan ADD COLUMN IF NOT EXISTS denyut_aktif  integer NOT NULL DEFAULT 0;
ALTER TABLE ielts_pengerjaan ADD COLUMN IF NOT EXISTS ronde         integer NOT NULL DEFAULT 1;

CREATE TABLE IF NOT EXISTS ielts_pelanggaran (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  pengerjaan_id integer NOT NULL,
  user_id integer NOT NULL,
  paket_id integer NOT NULL,
  subtes text,
  jenis text NOT NULL DEFAULT 'keluar_tab',
  urutan integer NOT NULL DEFAULT 1,
  ronde integer NOT NULL DEFAULT 1,
  mulai_at timestamptz NOT NULL DEFAULT now(),
  kembali_at timestamptz,
  durasi_detik integer,
  keterangan text,
  kejadian text,
  PRIMARY KEY (id),
  FOREIGN KEY (paket_id) REFERENCES ielts_paket (id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (pengerjaan_id) REFERENCES ielts_pengerjaan (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_ielts_vio_kerja ON ielts_pelanggaran(pengerjaan_id, urutan);
CREATE INDEX IF NOT EXISTS idx_ielts_vio_paket ON ielts_pelanggaran(paket_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_ielts_vio_kejadian
  ON ielts_pelanggaran(pengerjaan_id, kejadian) WHERE kejadian IS NOT NULL;

COMMIT;
